apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: hello-controller
  namespace: crossplane-system
  labels:
    core.crossplane.io/name: "crossplane-sample-extension-installer"
    app.kubernetes.io/managed-by: "stax"
spec:
  generateSelector: true
  parentResource:
    apiVersion: sample.crossplane.io/v1
    resource: helloworlds
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://hello-controller.crossplane-system/sync
