# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- controller.yaml
- webhook.yaml

# namespace to deploy all Resources to
# inherited from kubectl
# namespace: default

# labels added to all Resources
commonLabels:
  app: sample-extension-metacontroller
  app.kubernetes.io/managed-by: "crossplane-stacks"

configMapGenerator:
- name: hello-controller
  files:
  - sync.py

