---
# TODO(displague) include the metacontroller deployment and rbac here for now
# extension manager should become aware of predetermined managers and verify (how?) or install these managers
# (dependencies) before installing the extension.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.sample.crossplane.io
spec:
  group: sample.crossplane.io
  version: v1
  names:
    kind: HelloWorld
    plural: helloworlds
    singular: helloworld
  scope: Namespaced
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            who:
              type: string
